[build-system]
requires = [
    "setuptools",
    "wheel",
    "oldest-supported-numpy",
    "scipy",
    "cython"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--junitxml=junit/test-results.xml --strict-markers"
markers = [    
    "slow",
    "notebook",
    "automl",
    "dml",
    "half"
]